export { BeforeWeProceed } from "./before-we-proceed"
export { OptimizationPattern1 } from "./optimization-pattern1"
export { OptimizationPattern1Solution } from "./optimization-pattern1-solution"
export { OptimizationPattern2 } from "./optimization-pattern2"
export { OptimizationPattern2Solution } from "./optimization-pattern2-solution"
export { OptimizationPattern3 } from "./optimization-pattern3"
export { OptimizationPattern3Solution } from "./optimization-pattern3-solution"